[sdl]
output = opengl
windowresolution = 1024x768

[dosbox]
machine = svga_et4000
memsize = 255

[cpu]
core = dynamic
cputype = pentium_mmx
cycles = 120000

[video]
vmemsize = 4
vesa modelist = 1024x768 640x480 800x600
vesa old vbe = true
vesa write modes = linear

[sblaster]
sbtype = sb16
sbbase = 220
irq = 7
dma = 1
hdma = 5

[ide, primary]
enable = true

[ide, secondary]
enable = true

[autoexec]
imgmount c "/var/home/longjoel/Projects/voff/isos/win98_hdd.img" -size 512,63,64,1024
imgmount d "/var/home/longjoel/Projects/voff/von.img" -t iso
imgmount a "/var/home/longjoel/Projects/voff/isos/softgpu_drivers.img" -t floppy
boot -l c
