#!/usr/bin/env python3
"""gen_game.py — scan game/*.c and generate game.h + stub_funcs.c

Usage:
  python3 gen_game.py game/
"""

import re
import sys
import os
import glob

dest_dir = sys.argv[1] if len(sys.argv) > 1 else "game"

# Collect all function definitions from game/*.c
defined_funcs = {}
for fpath in sorted(glob.glob(os.path.join(dest_dir, "*.c"))):
    with open(fpath) as f:
        content = f.read()
    # Strip comment lines and #include lines before regex matching
    stripped = '\n'.join(
        line for line in content.split('\n')
        if not line.strip().startswith('/*') and not line.strip().startswith('*')
        and not line.strip().startswith('#include') and not line.strip().startswith('//')
    )
    # Find: return_type FUN_XXXXXXXX__desc(params)
    m = re.search(
        r'(\w[\w\s*]+?)\s+(FUN_[0-9a-fA-F]{8}__\w+)\s*\(([^)]*)\)',
        stripped
    )
    if m:
        ret = ' '.join(m.group(1).split())
        fname = m.group(2)
        params = m.group(3).strip()
        # Skip if ret looks like garbage
        if '/*' not in ret and '#include' not in ret:
            defined_funcs[fname] = (ret, params)

# Collect all FUN_ calls from game/*.c that are NOT defined
called_funcs = set()
for fpath in sorted(glob.glob(os.path.join(dest_dir, "*.c"))):
    with open(fpath) as f:
        content = f.read()
    for m in re.finditer(r'\b(FUN_[0-9a-fA-F]{8})\b', content):
        called_funcs.add(m.group(1))

# Functions that are called but not defined in game/ need stubs
# (functions with "__" suffix are defined here, bare FUN_ are from decompiled src)
# Actually: any FUN_XXXXXXXX referenced but not in defined_funcs needs a stub.
# defined_funcs keys have __desc suffix. called_funcs are bare FUN_XXXXXXXX.
stub_funcs = set()
for f in sorted(called_funcs):
    # Check if any defined function starts with this prefix (base name match)
    found = any(df.startswith(f) for df in defined_funcs)
    if not found:
        stub_funcs.add(f)

# Collect all DAT_, PTR_, and similar global references from game/*.c
data_globals = set()
for fpath in sorted(glob.glob(os.path.join(dest_dir, "*.c"))):
    with open(fpath) as f:
        content = f.read()
    for m in re.finditer(r'\b(DAT_[0-9a-fA-F]{8})\b', content):
        data_globals.add(m.group(1))
    for m in re.finditer(r'\b(PTR_[A-Za-z_][A-Za-z0-9_]{1,40})\b', content):
        g = m.group(1)
        if not g.startswith('PTR_FUN_'):
            data_globals.add(g)
    # Also catch _DAT_ prefixed globals
    for m in re.finditer(r'\b(_DAT_[0-9a-fA-F]{8})\b', content):
        data_globals.add(m.group(1))

# Generate game.h
header_lines = []
header_lines.append("/* Auto-generated by gen_game.py */\n")
header_lines.append("#ifndef VOFF_GAME_H\n")
header_lines.append("#define VOFF_GAME_H\n\n")
header_lines.append('#include "../voff_bridge.h"\n')
header_lines.append("typedef long double float10;\n\n")

# Data section globals
if data_globals:
    header_lines.append(f"/* === Data section globals ({len(data_globals)} symbols) === */\n")
    for g in sorted(data_globals):
        if g.startswith('DAT_') or g.startswith('_DAT_'):
            # Strip leading underscore for hex parse
            clean = g[1:] if g.startswith('_') else g
            m = re.match(r'DAT_([0-9a-fA-F]{8})', clean)
            if m:
                va = int(m.group(1), 16)
                offset = va - 0x0063F000
                header_lines.append(f"#define {g} (*(uint32_t*)(__data_start + {offset}))\n")
            else:
                header_lines.append(f"extern uint32_t {g};\n")
        else:
            header_lines.append(f"extern uint8_t {g}[4096];\n")
    header_lines.append("\n")
header_lines.append('#include "dat_overrides.h"\n\n')

# Estimate argument count for stub functions (max args seen in calls)
stub_arg_counts = {}
for fpath in sorted(glob.glob(os.path.join(dest_dir, "*.c"))):
    if 'stub_funcs' in fpath:
        continue
    with open(fpath) as f:
        content = f.read()
    for fname in stub_funcs:
        pattern = re.escape(fname) + r'\s*\(([^)]*)\)'
        for m in re.finditer(pattern, content):
            args = m.group(1).strip()
            if args:
                n = args.count(',') + 1
                if fname not in stub_arg_counts or n > stub_arg_counts[fname]:
                    stub_arg_counts[fname] = n
            elif fname not in stub_arg_counts:
                stub_arg_counts[fname] = 0

# Write defined function declarations
header_lines.append("/* === Game functions (compiled from decompiled source) === */\n")
for fname, (ret, params) in sorted(defined_funcs.items()):
    header_lines.append(f"extern {ret} {fname}({params});\n")

# Generate aliases: FUN_XXXXXXXX -> FUN_XXXXXXXX__descriptive_name
# so that calls to the original name resolve to the renamed function
header_lines.append("\n/* === Function name aliases === */\n")
for fname in sorted(defined_funcs.keys()):
    base = fname.split('__')[0] if '__' in fname else fname
    if base != fname:
        header_lines.append(f"#define {base} {fname}\n")

# Write stub declarations
header_lines.append("\n/* === Stub declarations (called but not yet translated) === */\n")
for fname in sorted(stub_funcs):
    n = stub_arg_counts.get(fname, 0)
    if n:
        args = ", ".join(f"int a{i}" for i in range(n))
        header_lines.append(f"extern int {fname}({args});\n")
    else:
        header_lines.append(f"extern void {fname}(void);\n")

header_lines.append("\n#endif\n")

with open(os.path.join(dest_dir, "game.h"), 'w') as f:
    f.writelines(header_lines)

# Generate stub_funcs.c
stub_lines = []
stub_lines.append("/* Auto-generated stub functions */\n")
stub_lines.append('#include "game.h"\n\n')

for fname in sorted(stub_funcs):
    n = stub_arg_counts.get(fname, 0)
    if n:
        args = ", ".join(f"int a{i}" for i in range(n))
        stub_lines.append(f"int {fname}({args}) {{ return 0; }}\n")
    else:
        stub_lines.append(f"void {fname}(void) {{ }}\n")

with open(os.path.join(dest_dir, "stub_funcs.c"), 'w') as f:
    f.writelines(stub_lines)

print(f"Generated game.h: {len(defined_funcs)} declarations, {len(stub_funcs)} stubs")
print(f"Generated stub_funcs.c: {len(stub_funcs)} stub bodies")
for f in sorted(stub_funcs):
    print(f"  {f}")
