/* Auto-generated by gen_game.py */
#ifndef VOFF_GAME_H
#define VOFF_GAME_H

#include "../voff_bridge.h"
typedef long double float10;

/* === Data section globals (163 symbols) === */
#define DAT_005f8890 (*(uint32_t*)(__data_start + 6260880))
#define DAT_005f8894 (*(uint32_t*)(__data_start + 6260884))
#define DAT_005fb140 (*(uint32_t*)(__data_start + 6271296))
#define DAT_005fb198 (*(uint32_t*)(__data_start + 6271384))
#define DAT_005fb2d8 (*(uint32_t*)(__data_start + 6271704))
#define DAT_005fb2dc (*(uint32_t*)(__data_start + 6271708))
#define DAT_005fd6d0 (*(uint32_t*)(__data_start + 6280912))
#define DAT_005fd6d4 (*(uint32_t*)(__data_start + 6280916))
#define DAT_005fda1c (*(uint32_t*)(__data_start + 6281756))
#define DAT_005fda40 (*(uint32_t*)(__data_start + 6281792))
#define DAT_005fda44 (*(uint32_t*)(__data_start + 6281796))
#define DAT_005fda50 (*(uint32_t*)(__data_start + 6281808))
#define DAT_005fda54 (*(uint32_t*)(__data_start + 6281812))
#define DAT_005fda80 (*(uint32_t*)(__data_start + 6281856))
#define DAT_005fda84 (*(uint32_t*)(__data_start + 6281860))
#define DAT_005fda88 (*(uint32_t*)(__data_start + 6281864))
#define DAT_005fda8c (*(uint32_t*)(__data_start + 6281868))
#define DAT_005fdad0 (*(uint32_t*)(__data_start + 6281936))
#define DAT_005fdad4 (*(uint32_t*)(__data_start + 6281940))
#define DAT_00600e88 (*(uint32_t*)(__data_start + 6295176))
#define DAT_00600ea8 (*(uint32_t*)(__data_start + 6295208))
#define DAT_006471e0 (*(uint32_t*)(__data_start + 6582752))
#define DAT_006471e4 (*(uint32_t*)(__data_start + 6582756))
#define DAT_006471e8 (*(uint32_t*)(__data_start + 6582760))
#define DAT_006536cc (*(uint32_t*)(__data_start + 6633164))
#define DAT_006537b8 (*(uint32_t*)(__data_start + 6633400))
#define DAT_0066c178 (*(uint32_t*)(__data_start + 6734200))
#define DAT_0066c1a0 (*(uint32_t*)(__data_start + 6734240))
#define DAT_0066c1a8 (*(uint32_t*)(__data_start + 6734248))
#define DAT_0066c1ac (*(uint32_t*)(__data_start + 6734252))
#define DAT_006bc948 (*(uint32_t*)(__data_start + 7063880))
#define DAT_006bc94c (*(uint32_t*)(__data_start + 7063884))
#define DAT_006bf444 (*(uint32_t*)(__data_start + 7074884))
#define DAT_006bf448 (*(uint32_t*)(__data_start + 7074888))
#define DAT_006bf598 (*(uint32_t*)(__data_start + 7075224))
#define DAT_006bf5a0 (*(uint32_t*)(__data_start + 7075232))
#define DAT_006c84d0 (*(uint32_t*)(__data_start + 7111888))
#define DAT_006db520 (*(uint32_t*)(__data_start + 7189792))
#define DAT_006db524 (*(uint32_t*)(__data_start + 7189796))
#define DAT_006db528 (*(uint32_t*)(__data_start + 7189800))
#define DAT_007087e0 (*(uint32_t*)(__data_start + 7374816))
#define DAT_00791a58 (*(uint32_t*)(__data_start + 7936600))
#define DAT_007a24b8 (*(uint32_t*)(__data_start + 8004792))
#define DAT_007a347c (*(uint32_t*)(__data_start + 8008828))
#define DAT_007a3740 (*(uint32_t*)(__data_start + 8009536))
#define DAT_007b5278 (*(uint32_t*)(__data_start + 8082040))
#define DAT_007b56d4 (*(uint32_t*)(__data_start + 8083156))
#define DAT_007b5790 (*(uint32_t*)(__data_start + 8083344))
#define DAT_007e7c58 (*(uint32_t*)(__data_start + 8289368))
#define DAT_007e7cb8 (*(uint32_t*)(__data_start + 8289464))
#define DAT_007e82c0 (*(uint32_t*)(__data_start + 8291008))
#define DAT_007e83c8 (*(uint32_t*)(__data_start + 8291272))
#define DAT_007e83d8 (*(uint32_t*)(__data_start + 8291288))
#define DAT_007e87e8 (*(uint32_t*)(__data_start + 8292328))
#define DAT_009055b4 (*(uint32_t*)(__data_start + 9459124))
#define DAT_00913a90 (*(uint32_t*)(__data_start + 9517712))
#define DAT_009e6b34 (*(uint32_t*)(__data_start + 10382132))
#define DAT_009ebccc (*(uint32_t*)(__data_start + 10403020))
#define DAT_009ebd14 (*(uint32_t*)(__data_start + 10403092))
#define DAT_009ebd44 (*(uint32_t*)(__data_start + 10403140))
#define DAT_00a00a1c (*(uint32_t*)(__data_start + 10488348))
#define DAT_00bf5f78 (*(uint32_t*)(__data_start + 12541816))
#define DAT_00bf5f7c (*(uint32_t*)(__data_start + 12541820))
#define DAT_00bf6f1c (*(uint32_t*)(__data_start + 12545820))
#define DAT_00bf6f50 (*(uint32_t*)(__data_start + 12545872))
#define DAT_00bf7758 (*(uint32_t*)(__data_start + 12547928))
#define DAT_00bf775c (*(uint32_t*)(__data_start + 12547932))
#define DAT_01ae1c1c (*(uint32_t*)(__data_start + 28187676))
#define DAT_01ae1ffc (*(uint32_t*)(__data_start + 28188668))
#define DAT_01ae2004 (*(uint32_t*)(__data_start + 28188676))
#define DAT_01ae2014 (*(uint32_t*)(__data_start + 28188692))
#define DAT_01ae2556 (*(uint32_t*)(__data_start + 28190038))
#define DAT_01ae255b (*(uint32_t*)(__data_start + 28190043))
#define DAT_01ae255c (*(uint32_t*)(__data_start + 28190044))
#define DAT_01ae2560 (*(uint32_t*)(__data_start + 28190048))
#define DAT_01ae2561 (*(uint32_t*)(__data_start + 28190049))
#define DAT_01ae2e10 (*(uint32_t*)(__data_start + 28192272))
#define DAT_01ae2e1c (*(uint32_t*)(__data_start + 28192284))
#define DAT_01ae2e28 (*(uint32_t*)(__data_start + 28192296))
#define DAT_01ae3362 (*(uint32_t*)(__data_start + 28193634))
#define DAT_01ae3528 (*(uint32_t*)(__data_start + 28194088))
#define DAT_01ae353c (*(uint32_t*)(__data_start + 28194108))
#define DAT_01ae354c (*(uint32_t*)(__data_start + 28194124))
#define DAT_01ae3554 (*(uint32_t*)(__data_start + 28194132))
#define DAT_01ae3594 (*(uint32_t*)(__data_start + 28194196))
#define DAT_01ae3598 (*(uint32_t*)(__data_start + 28194200))
#define DAT_01ae35a0 (*(uint32_t*)(__data_start + 28194208))
#define DAT_01ae3690 (*(uint32_t*)(__data_start + 28194448))
#define DAT_01ae61e0 (*(uint32_t*)(__data_start + 28205536))
#define DAT_01caf4a2 (*(uint32_t*)(__data_start + 30078114))
#define DAT_01caf4ba (*(uint32_t*)(__data_start + 30078138))
#define DAT_01caf4bf (*(uint32_t*)(__data_start + 30078143))
#define DAT_01caf4c0 (*(uint32_t*)(__data_start + 30078144))
#define DAT_01caf4c4 (*(uint32_t*)(__data_start + 30078148))
#define DAT_01caf4c5 (*(uint32_t*)(__data_start + 30078149))
#define DAT_01caf4d4 (*(uint32_t*)(__data_start + 30078164))
#define DAT_01caf4d8 (*(uint32_t*)(__data_start + 30078168))
#define DAT_01cb14a0 (*(uint32_t*)(__data_start + 30086304))
#define DAT_01cb14c2 (*(uint32_t*)(__data_start + 30086338))
#define DAT_01cb1500 (*(uint32_t*)(__data_start + 30086400))
#define DAT_01cb2a20 (*(uint32_t*)(__data_start + 30091808))
#define DAT_01cb3440 (*(uint32_t*)(__data_start + 30094400))
#define DAT_01cb3460 (*(uint32_t*)(__data_start + 30094432))
#define DAT_01cb34c0 (*(uint32_t*)(__data_start + 30094528))
#define DAT_01cc1500 (*(uint32_t*)(__data_start + 30151936))
#define DAT_01ed5e1e (*(uint32_t*)(__data_start + 32333342))
#define DAT_01ed5e22 (*(uint32_t*)(__data_start + 32333346))
#define DAT_01ed5ea0 (*(uint32_t*)(__data_start + 32333472))
#define DAT_01ed5ec4 (*(uint32_t*)(__data_start + 32333508))
#define DAT_01ed5ed4 (*(uint32_t*)(__data_start + 32333524))
#define DAT_034155c4 (*(uint32_t*)(__data_start + 54613444))
#define DAT_034155c6 (*(uint32_t*)(__data_start + 54613446))
#define DAT_034155c8 (*(uint32_t*)(__data_start + 54613448))
#define DAT_034155cc (*(uint32_t*)(__data_start + 54613452))
#define DAT_034155ce (*(uint32_t*)(__data_start + 54613454))
#define DAT_034155d0 (*(uint32_t*)(__data_start + 54613456))
#define DAT_034155d2 (*(uint32_t*)(__data_start + 54613458))
#define DAT_034155d4 (*(uint32_t*)(__data_start + 54613460))
#define DAT_034155e4 (*(uint32_t*)(__data_start + 54613476))
#define DAT_03415608 (*(uint32_t*)(__data_start + 54613512))
#define DAT_03415611 (*(uint32_t*)(__data_start + 54613521))
#define DAT_0345b17c (*(uint32_t*)(__data_start + 54899068))
#define DAT_0345b180 (*(uint32_t*)(__data_start + 54899072))
#define DAT_0345b280 (*(uint32_t*)(__data_start + 54899328))
#define DAT_0345b284 (*(uint32_t*)(__data_start + 54899332))
#define DAT_0345b288 (*(uint32_t*)(__data_start + 54899336))
#define DAT_0345b290 (*(uint32_t*)(__data_start + 54899344))
#define DAT_0345b294 (*(uint32_t*)(__data_start + 54899348))
#define DAT_0345b298 (*(uint32_t*)(__data_start + 54899352))
#define DAT_0345b2a8 (*(uint32_t*)(__data_start + 54899368))
#define DAT_0345b2c0 (*(uint32_t*)(__data_start + 54899392))
#define DAT_0345b2c4 (*(uint32_t*)(__data_start + 54899396))
#define DAT_0345b2c8 (*(uint32_t*)(__data_start + 54899400))
#define DAT_0345b2d4 (*(uint32_t*)(__data_start + 54899412))
#define DAT_0345bd10 (*(uint32_t*)(__data_start + 54902032))
#define DAT_0345bd20 (*(uint32_t*)(__data_start + 54902048))
#define DAT_0345bd24 (*(uint32_t*)(__data_start + 54902052))
#define DAT_0345bd28 (*(uint32_t*)(__data_start + 54902056))
#define DAT_0345bd38 (*(uint32_t*)(__data_start + 54902072))
#define DAT_0345d420 (*(uint32_t*)(__data_start + 54907936))
#define DAT_0353e420 (*(uint32_t*)(__data_start + 55829536))
#define DAT_03656878 (*(uint32_t*)(__data_start + 56977528))
#define DAT_0365b988 (*(uint32_t*)(__data_start + 56998280))
extern uint8_t PTR_DAT_00646ff0[4096];
#define _DAT_005fb2d0 (*(uint32_t*)(__data_start + 6271696))
#define _DAT_005fb2e0 (*(uint32_t*)(__data_start + 6271712))
#define _DAT_005fb2e8 (*(uint32_t*)(__data_start + 6271720))
#define _DAT_005fb2f0 (*(uint32_t*)(__data_start + 6271728))
#define _DAT_005fb2f8 (*(uint32_t*)(__data_start + 6271736))
#define _DAT_005fb308 (*(uint32_t*)(__data_start + 6271752))
#define _DAT_005fb310 (*(uint32_t*)(__data_start + 6271760))
#define _DAT_006a0568 (*(uint32_t*)(__data_start + 6948200))
#define _DAT_00bf7748 (*(uint32_t*)(__data_start + 12547912))
#define _DAT_00bf7764 (*(uint32_t*)(__data_start + 12547940))
#define _DAT_01ae2e24 (*(uint32_t*)(__data_start + 28192292))
#define _DAT_01ae35d8 (*(uint32_t*)(__data_start + 28194264))
#define _DAT_01ae3634 (*(uint32_t*)(__data_start + 28194356))
#define _DAT_01cb14c4 (*(uint32_t*)(__data_start + 30086340))
#define _DAT_01cb14c6 (*(uint32_t*)(__data_start + 30086342))
#define _DAT_034155c0 (*(uint32_t*)(__data_start + 54613440))
#define _DAT_034155ca (*(uint32_t*)(__data_start + 54613450))
#define _DAT_034155d8 (*(uint32_t*)(__data_start + 54613464))
#define _DAT_0365143c (*(uint32_t*)(__data_start + 56955964))

#include "dat_overrides.h"

/* === Game functions (compiled from decompiled source) === */
extern void FUN_004086e0__render_prep(void);
extern void FUN_0040ef60__matrix_translate(float param_1,float param_2,float param_3);
extern void FUN_004224d0__matrix_scale(float param_1,float param_2,float param_3);
extern void FUN_0042ca55__sprite_draw(char param_1,uint32_t param_2,float param_3,uint32_t param_4,
                 uint32_t param_5,float param_6,int param_7,int param_8);
extern void FUN_00442ce1__input_poll(void);
extern void FUN_0044a670__sprite_render_slot(int param_1,int param_2);
extern void FUN_0044ac4a__sprite_render_slot2(uint32_t param_1,int param_2);
extern void FUN_0044ae55__title_anim_dispatch(int param_1);
extern void FUN_0044af3d__title_init(void);
extern void FUN_0044af8d__title_anim_setup(void);
extern void FUN_0044b042__title_display_loop(void);
extern void FUN_0044b184__title_delay1(void);
extern void FUN_0044b195__title_delay2(void);
extern void FUN_0044b1a6__title_setup(void);
extern void FUN_0044b38c__title_screen_dispatch(void);
extern void FUN_00476620__state0_handler(void);
extern uint32_t FUN_00483200__arena_setup(void);
extern void FUN_0049f8e8__state_dispatcher(void);
extern void FUN_004a6ab0__slot_setup(void);
extern uint32_t FUN_004a6b09__slot_alloc(void);
extern void FUN_004b15f0__ingame_init(void);
extern void FUN_004b1841__ingame_setup1(void);
extern void FUN_004b1b52__ingame_setup2(void);
extern void FUN_004b1ca7__ingame(void);
extern void FUN_004cd19e__sprite_load(int param_1);
extern void FUN_004cd25c__sprite_init(void);
extern void FUN_004cd542__anim_schedule(void);
extern void FUN_004cda9f__set_fade_mode(uint16_t param_1);
extern void FUN_00514576__render_submit(uint param_1, uint param_2, uint param_3, int param_4);
extern void FUN_00514639__matrix_position(float param_1, float param_2, float param_3);
extern void FUN_005cc380__d3d_begin(void);
extern void FUN_005cc4c6__d3d_submit(uint param_1, uint param_2, uint param_3, int param_4);

/* === Function name aliases === */
#define FUN_004086e0 FUN_004086e0__render_prep
#define FUN_0040ef60 FUN_0040ef60__matrix_translate
#define FUN_004224d0 FUN_004224d0__matrix_scale
#define FUN_0042ca55 FUN_0042ca55__sprite_draw
#define FUN_00442ce1 FUN_00442ce1__input_poll
#define FUN_0044a670 FUN_0044a670__sprite_render_slot
#define FUN_0044ac4a FUN_0044ac4a__sprite_render_slot2
#define FUN_0044ae55 FUN_0044ae55__title_anim_dispatch
#define FUN_0044af3d FUN_0044af3d__title_init
#define FUN_0044af8d FUN_0044af8d__title_anim_setup
#define FUN_0044b042 FUN_0044b042__title_display_loop
#define FUN_0044b184 FUN_0044b184__title_delay1
#define FUN_0044b195 FUN_0044b195__title_delay2
#define FUN_0044b1a6 FUN_0044b1a6__title_setup
#define FUN_0044b38c FUN_0044b38c__title_screen_dispatch
#define FUN_00476620 FUN_00476620__state0_handler
#define FUN_00483200 FUN_00483200__arena_setup
#define FUN_0049f8e8 FUN_0049f8e8__state_dispatcher
#define FUN_004a6ab0 FUN_004a6ab0__slot_setup
#define FUN_004a6b09 FUN_004a6b09__slot_alloc
#define FUN_004b15f0 FUN_004b15f0__ingame_init
#define FUN_004b1841 FUN_004b1841__ingame_setup1
#define FUN_004b1b52 FUN_004b1b52__ingame_setup2
#define FUN_004b1ca7 FUN_004b1ca7__ingame
#define FUN_004cd19e FUN_004cd19e__sprite_load
#define FUN_004cd25c FUN_004cd25c__sprite_init
#define FUN_004cd542 FUN_004cd542__anim_schedule
#define FUN_004cda9f FUN_004cda9f__set_fade_mode
#define FUN_00514576 FUN_00514576__render_submit
#define FUN_00514639 FUN_00514639__matrix_position
#define FUN_005cc380 FUN_005cc380__d3d_begin
#define FUN_005cc4c6 FUN_005cc4c6__d3d_submit

/* === Stub declarations (called but not yet translated) === */
extern void FUN_00408630(void);
extern void FUN_004086b0(void);
extern int FUN_00408720(int a0, int a1, int a2);
extern int FUN_00408790(int a0, int a1, int a2);
extern int FUN_004089e0(int a0);
extern int FUN_00408a00(int a0);
extern int FUN_0042c999(int a0, int a1, int a2);
extern void FUN_0044b1ef(void);
extern void FUN_0046270d(void);
extern int FUN_0047f0c0(int a0, int a1);
extern void FUN_00480f10(void);
extern int FUN_00480f30(int a0, int a1);
extern void FUN_0049f82c(void);
extern void FUN_0049fa26(void);
extern void FUN_0049fb9b(void);
extern void FUN_0049fbc0(void);
extern int FUN_004a38a0(int a0);
extern void FUN_004a6b68(void);
extern int FUN_004a6c0a(int a0);
extern int FUN_004a6f70(int a0, int a1);
extern int FUN_004a70c6(int a0);
extern int FUN_004cd0a0(int a0, int a1, int a2);
extern void FUN_004cd2bc(void);
extern int FUN_004cd8c3(int a0, int a1);
extern int FUN_004cf4cc(int a0, int a1);
extern void FUN_004cf5c9(void);
extern int FUN_004d020a(int a0);
extern void FUN_004d026a(void);
extern int FUN_004d0275(int a0, int a1);
extern int FUN_004d04f8(int a0);
extern int FUN_004d11cd(int a0);
extern int FUN_004d1328(int a0);
extern int FUN_004d13dc(int a0, int a1);
extern void FUN_00514430(void);
extern void FUN_0051456b(void);
extern void FUN_00545d20(void);
extern void FUN_00545dfa(void);
extern void FUN_0054618b(void);
extern void FUN_0056240a(void);
extern void FUN_00589923(void);
extern int FUN_00597311(int a0);
extern int FUN_00597365(int a0);
extern int FUN_005973a0(int a0);
extern int FUN_00597433(int a0);
extern void FUN_005c017d(void);
extern void FUN_005c0226(void);
extern int FUN_005c45e0(int a0);
extern int FUN_005cacb0(int a0, int a1, int a2, int a3);
extern int FUN_005cafc0(int a0);
extern void FUN_005d2fa0(void);
extern void FUN_005dde70(void);
extern int FUN_005e6230(int a0);

#endif
