/* Auto-generated by gen_game.py */
#ifndef VOFF_GAME_H
#define VOFF_GAME_H

#include "../voff_bridge.h"

/* === Data section globals (59 symbols) === */
#define DAT_005fb140 (*(uint32_t*)(__data_start + -278208))
#define DAT_005fb198 (*(uint32_t*)(__data_start + -278120))
#define DAT_00600e88 (*(uint32_t*)(__data_start + -254328))
#define DAT_00600ea8 (*(uint32_t*)(__data_start + -254296))
#define DAT_006537b8 (*(uint32_t*)(__data_start + 83896))
#define DAT_006bc94c (*(uint32_t*)(__data_start + 514380))
#define DAT_00bf7758 (*(uint32_t*)(__data_start + 5998424))
#define DAT_00bf775c (*(uint32_t*)(__data_start + 5998428))
#define DAT_01ae1c1c (*(uint32_t*)(__data_start + 21638172))
#define DAT_01ae2004 (*(uint32_t*)(__data_start + 21639172))
#define DAT_01ae2014 (*(uint32_t*)(__data_start + 21639188))
#define DAT_01ae3528 (*(uint32_t*)(__data_start + 21644584))
#define DAT_01ae353c (*(uint32_t*)(__data_start + 21644604))
#define DAT_01ae3594 (*(uint32_t*)(__data_start + 21644692))
#define DAT_01ae3690 (*(uint32_t*)(__data_start + 21644944))
#define DAT_01caf4a2 (*(uint32_t*)(__data_start + 23528610))
#define DAT_01caf4d4 (*(uint32_t*)(__data_start + 23528660))
#define DAT_01caf4d8 (*(uint32_t*)(__data_start + 23528664))
#define DAT_01cb1500 (*(uint32_t*)(__data_start + 23536896))
#define DAT_01cb2a20 (*(uint32_t*)(__data_start + 23542304))
#define DAT_01cb3440 (*(uint32_t*)(__data_start + 23544896))
#define DAT_01cb3460 (*(uint32_t*)(__data_start + 23544928))
#define DAT_01cb34c0 (*(uint32_t*)(__data_start + 23545024))
#define DAT_01cc1500 (*(uint32_t*)(__data_start + 23602432))
#define DAT_01ed5e1e (*(uint32_t*)(__data_start + 25783838))
#define DAT_01ed5e22 (*(uint32_t*)(__data_start + 25783842))
#define DAT_01ed5ea0 (*(uint32_t*)(__data_start + 25783968))
#define DAT_01ed5ec4 (*(uint32_t*)(__data_start + 25784004))
#define DAT_01ed5ed4 (*(uint32_t*)(__data_start + 25784020))
#define DAT_034155c4 (*(uint32_t*)(__data_start + 48063940))
#define DAT_034155c6 (*(uint32_t*)(__data_start + 48063942))
#define DAT_034155c8 (*(uint32_t*)(__data_start + 48063944))
#define DAT_034155cc (*(uint32_t*)(__data_start + 48063948))
#define DAT_034155ce (*(uint32_t*)(__data_start + 48063950))
#define DAT_034155d0 (*(uint32_t*)(__data_start + 48063952))
#define DAT_034155d2 (*(uint32_t*)(__data_start + 48063954))
#define DAT_034155d4 (*(uint32_t*)(__data_start + 48063956))
#define DAT_034155e4 (*(uint32_t*)(__data_start + 48063972))
#define DAT_03415608 (*(uint32_t*)(__data_start + 48064008))
#define DAT_03415611 (*(uint32_t*)(__data_start + 48064017))
#define DAT_0345b17c (*(uint32_t*)(__data_start + 48349564))
#define DAT_0345b180 (*(uint32_t*)(__data_start + 48349568))
#define DAT_0345b280 (*(uint32_t*)(__data_start + 48349824))
#define DAT_0345b284 (*(uint32_t*)(__data_start + 48349828))
#define DAT_0345b288 (*(uint32_t*)(__data_start + 48349832))
#define DAT_0345bd10 (*(uint32_t*)(__data_start + 48352528))
#define DAT_0345bd20 (*(uint32_t*)(__data_start + 48352544))
#define DAT_0345bd24 (*(uint32_t*)(__data_start + 48352548))
#define DAT_0365b988 (*(uint32_t*)(__data_start + 50448776))
#define _DAT_006a0568 (*(uint32_t*)(__data_start + 398696))
#define _DAT_00bf7748 (*(uint32_t*)(__data_start + 5998408))
#define _DAT_00bf7764 (*(uint32_t*)(__data_start + 5998436))
#define _DAT_01ae2e24 (*(uint32_t*)(__data_start + 21642788))
#define _DAT_01ae35d8 (*(uint32_t*)(__data_start + 21644760))
#define _DAT_01ae3634 (*(uint32_t*)(__data_start + 21644852))
#define _DAT_034155c0 (*(uint32_t*)(__data_start + 48063936))
#define _DAT_034155ca (*(uint32_t*)(__data_start + 48063946))
#define _DAT_034155d8 (*(uint32_t*)(__data_start + 48063960))
#define _DAT_0365143c (*(uint32_t*)(__data_start + 50406460))

#include "dat_overrides.h"

/* === Game functions (compiled from decompiled source) === */
extern void FUN_0040ef60__matrix_translate(float param_1,float param_2,float param_3);
extern void FUN_004224d0__matrix_scale(float param_1,float param_2,float param_3);
extern void FUN_0044af3d__title_init(void);
extern void FUN_0044af8d__title_anim_setup(void);
extern void FUN_0044b042__title_display_loop(void);
extern void FUN_0044b184__title_delay1(void);
extern void FUN_0044b195__title_delay2(void);
extern void FUN_0044b1a6__title_setup(void);
extern void FUN_0044b38c__title_screen_dispatch(void);
extern void FUN_0049f8e8__state_dispatcher(void);
extern void FUN_004a6ab0__slot_setup(void);
extern uint32_t FUN_004a6b09__slot_alloc(void);
extern void FUN_004cd19e__sprite_load(int param_1);
extern void FUN_004cd25c__sprite_init(void);
extern void FUN_004cd542__anim_schedule(void);
extern void FUN_004cda9f__set_fade_mode(uint16_t param_1);

/* === Function name aliases === */
#define FUN_0040ef60 FUN_0040ef60__matrix_translate
#define FUN_004224d0 FUN_004224d0__matrix_scale
#define FUN_0044af3d FUN_0044af3d__title_init
#define FUN_0044af8d FUN_0044af8d__title_anim_setup
#define FUN_0044b042 FUN_0044b042__title_display_loop
#define FUN_0044b184 FUN_0044b184__title_delay1
#define FUN_0044b195 FUN_0044b195__title_delay2
#define FUN_0044b1a6 FUN_0044b1a6__title_setup
#define FUN_0044b38c FUN_0044b38c__title_screen_dispatch
#define FUN_0049f8e8 FUN_0049f8e8__state_dispatcher
#define FUN_004a6ab0 FUN_004a6ab0__slot_setup
#define FUN_004a6b09 FUN_004a6b09__slot_alloc
#define FUN_004cd19e FUN_004cd19e__sprite_load
#define FUN_004cd25c FUN_004cd25c__sprite_init
#define FUN_004cd542 FUN_004cd542__anim_schedule
#define FUN_004cda9f FUN_004cda9f__set_fade_mode

/* === Stub declarations (called but not yet translated) === */
extern void FUN_004086e0(void);
extern int FUN_0044ae55(int a0);
extern void FUN_0046270d(void);
extern void FUN_00480f10(void);
extern void FUN_0049f82c(void);
extern void FUN_0049fa26(void);
extern void FUN_0049fb9b(void);
extern int FUN_004a38a0(int a0);
extern void FUN_004a6b68(void);
extern int FUN_004a6c0a(int a0);
extern int FUN_004cd0a0(int a0, int a1, int a2);
extern void FUN_004cd2bc(void);
extern int FUN_004cd8c3(int a0, int a1);
extern int FUN_004d04f8(int a0);
extern void FUN_004d53ff(void);
extern void FUN_0051456b(void);
extern void FUN_00589923(void);
extern int FUN_00597311(int a0);
extern int FUN_00597365(int a0);
extern int FUN_005973a0(int a0);
extern void FUN_005c017d(void);

#endif
